global:
  scrape_interval:     15s
  scrape_timeout:      10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets:

scrape_configs:
  - job_name: 'prometheus'


    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: 'file_ds'
    file_sd_configs:
      - files:
          - "./files/*.json"