mysql:
  path: 127.0.0.1
  port: "3306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db_name: "magikarp"
  username: root
  password: "123456"

jwt:
  signing-key: "36468-sasdh-edasne"

redis:
  db: 0
  addr: 127.0.0.1:6379
  password: "123456"

mongo:
  host: 127.0.0.1
  port: "27017"
  username: "root"
  password: "123456"


zap:
  level: info
  prefix: '[github.com/oigi/Magikarp]'
  format: console
  director: logs
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  max-age: 0
  show-line: true
  log-in-console: true

etcd:
  address: 127.0.0.1:2379
  server:
    port: :4000
    version: 1.0
    jwtSecret: "38324-search-engine"
    metrics: 127.0.0.1:4000

  services:
    gateway:
      name: gateway
      loadBalance: true
      addr:
        - 127.0.0.1:20001
      metrics:
        - 127.0.0.1:30001

    user:
      name: user
      loadBalance: false
      addr:
        - 127.0.0.1:20002
      metrics:
        - 127.0.0.1:30002

    feed:
      name: feed
      loadBalance: true
      addr:
        - 127.0.0.1:20003
      metrics:
        - 127.0.0.1:30003

    favorite:
      name: favorite
      loadBalance: false
      addr:
        - 127.0.0.1:20004
      metrics:
        - 127.0.0.1:30004

    comment:
      name: comment
      loadBalance: false
      addr:
        - 127.0.0.1:20005
      metrics:
        - 127.0.0.1:30005

    publish:
      name: publish
      loadBalance: false
      addr:
        - 127.0.0.1:20006
      metrics:
        - 127.0.0.1:30006

    relation:
      name: relation
      loadBalance: false
      addr:
        - 127.0.0.1:20007
      metrics:
        - 127.0.0.1:30007

  domain:
    user:
      name: user
    favorite:
      name: favorite
    mapreduce:
      name: mapreduce
    publish:
      name: publish
    relation:
      name: relation
    comment:
      name: comment
    feed:
      name: feed

  milvus:
    host: 127.0.0.1
    port: 19530
    vector_dimension: 768
    default_milvus_table_name: milvus_table_name
    metric_type: L2
    timeout: 3

  jaeger:
    addr: 127.0.0.1:4317

